name = "custom-mytheme"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Minimal, brutalist-inspired Hugo theme."
min_version = "0.80.0"

[author]
  name = "Angelo Rodrigues"
